spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: company
          uri: http://${COMPANY_PATH:localhost}:8070
          predicates:
            - Path=/company/**
        - id: employee
          uri: http://${EMPLOYEE_PATH:localhost}:8090
          predicates:
            - Path=/employee/**

eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

management:
  tracing:
    sampling:
      probability: 1.0