spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: company
          uri: "lb://company/"
          predicates:
            - Path=/company/**
        - id: employee
          uri: "lb://employee/"
          predicates:
            - Path=/emp/**
eureka:
  client:
    register-with-eureka: true
server:
  port: 8222

